[[data]]
gotra = "shriivatsa"
pravara = ["bhRgu", "chyavana", "aapnavaana", "aurva", "jamadagni"]
suutra = "aapastamba"
veda_shaakhaas = ["yajurveda/taittiriiya"]
ancestral_districts = ["tumkur", "hassan"]
paternal_jaati = "hebbaar-ayyangaar"
id = "shriivatsa_aapastamba_south_ka/1"
data_provider = "23andme"
