[[data]]
gotra = "bhAradvAja"
pravara = ["AngIrasa", "bArhaspatya", "bhAradvAja"]
suutra = "aapastamba"
veda_shaakhaas = ["yajurveda/taittiriiya"]
ancestral_districts = ["lalgudi","varahur","pudukkottai"]
paternal_jaati = "brachcharaNam;mazhanAdu-brachcharaNam"
id = "bhAradvAja/TN/east/aapastamba/daya"
paternal_haplogroup = "L-M27"
maternal_haplogroup = "W3"
data_provider = "23andme"