[[data]]
gotra = "vAdhUla"
pravara = ["bhRgu", "vItahavya", "savetas"]
suutra = "aapastamba"
veda_shaakhaas = ["yajurveda/taittiriiya"]
ancestral_districts = ["chengalpattu", "thanjavur"]
paternal_jaati = "vaDagalai-ayyangaar"
id = "vaadhuula/KA/south_east/aapastamba/1"
paternal_haplogroup = "G-l30"
maternal_haplogroup = "U5a1"
data_provider = "23andme"
